sudo: required
dist: trusty
language: c
compiler:
- gcc
addons:
  apt:
    packages:
    - binutils-dev
    - genisoimage
    - liblzma-dev
    - syslinux
before_install:
- git clone --depth 1 https://github.com/ipxe/ipxe.git ipxe
- cp bootloader/ipxe/configs/* ipxe/src/config/local
- cd ipxe/src
script: 
- make bin/ipxe.dsk bin/ipxe.iso bin/ipxe.lkrn bin/ipxe.usb bin/ipxe.kpxe bin/undionly.kpxe bin-x86_64-efi/ipxe.efi
  EMBED=../../bootloader/ipxe/disks/rpc-deploy
after_success:
- mkdir ../../artifacts
- mv bin/ipxe.dsk ../../artifacts/rpc-deploy-bootloader.dsk
- mv bin/ipxe.iso ../../artifacts/rpc-deploy-bootloader.iso
- mv bin/ipxe.lkrn ../../artifacts/rpc-deploy-bootloader.lkrn
- mv bin/ipxe.usb ../../artifacts/rpc-deploy-bootloader.usb
- mv bin/ipxe.kpxe ../../artifacts/rpc-deploy-bootloader.kpxe
- mv bin/undionly.kpxe ../../artifacts/rpc-deploy-ipxe-bootloader.kpxe
- mv bin-x86_64-efi/ipxe.efi ../../artifacts/rpc-deploy-bootloader.efi
- cd ../../artifacts
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Antony Messerli"
  - git config --local user.email "amesserl@rackspace.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: "SfWYFswZbst3kMkqB3wgKSLtGwMYrVj5ZpuknqLNQoN6gF773pVRFE5w72LSlnMOlIIBGePodWymgoV0z50oSxjXKbC3dBZOkHDFpUeV4vzK7nZf7NLccW3G5yEDsCz0CPTSP/1GKvkV4hwgL/9YBVF/ZlT4S91W0NpDBlUWzFFHJ+m5UuR6wE67Ahlz5ezb0uRcrC/KMIYP5qK3Oo2t8DmO26So1dDLttGZ2s3U7++C4K+L/NnkR6lozJYJYfhe0WP67niXV7HaZ0YtpfNgvn6fKSqNEth1QPKMnjURrBxlKY/xo6MTK7BFvjLNbz/OHH9l7bKcd8/+dfdOPu0IP+OH55IlVs8uvwvCgzCQSxjfayPIg0Hd9M3lgIIyPqswIWmpcgjilIEw2ouq/1ztN1vKNKbn2sbmDVLjWckMOz6LviuIOrRPtDMuCJPm68W4P1nrMnpxmfVIW4E62Pca3JYrVOX71msHzlEq8NnWwIaYWlRk8slIReHAbj8IrNpZZVFLGpDNRb9BXJrD8Ja9BnjGT9m8s21bRXxptwJYmx9yAn0xocJDM8YA+WKjXTR5tZHZcDI90Qxs3oXu3W9TTrDF7xmgy2RQo+r41OwC9myEhP1rWUDjYRVzb4GUDhJz5InoTmuG/L1TDVZmpmCLqAWhrJUy61J+puG0fNVdvTE="
  file:
  - rpc-deploy-bootloader.dsk
  - rpc-deploy-bootloader.iso
  - rpc-deploy-bootloader.lkrn
  - rpc-deploy-bootloader.usb
  - rpc-deploy-bootloader.kpxe
  - rpc-deploy-bootloader.kpxe
  - rpc-deploy-bootloader.efi
  on:
    repo: rcbops/rpc-deploy
  skip_cleanup: true
