sudo: required
dist: xenial
language: c
compiler:
- gcc
addons:
  apt:
    packages:
    - binutils-dev
    - genisoimage
    - isolinux
    - liblzma-dev
    - syslinux
before_install:
- git clone --depth 1 https://github.com/ipxe/ipxe.git ipxe
- cp bootloader/ipxe/configs/* ipxe/src/config/local
- cd ipxe/src
script: 
- make bin/ipxe.dsk bin/ipxe.iso bin/ipxe.lkrn bin/ipxe.usb bin/ipxe.kpxe bin/undionly.kpxe bin-x86_64-efi/ipxe.efi
  EMBED=../../bootloader/ipxe/disks/rpc-deploy
after_success:
- mkdir ../../artifacts
- mv bin/ipxe.dsk ../../artifacts/rpc-deploy-bootloader.dsk
- mv bin/ipxe.iso ../../artifacts/rpc-deploy-bootloader.iso
- mv bin/ipxe.lkrn ../../artifacts/rpc-deploy-bootloader.lkrn
- mv bin/ipxe.usb ../../artifacts/rpc-deploy-bootloader.usb
- mv bin/ipxe.kpxe ../../artifacts/rpc-deploy-bootloader.kpxe
- mv bin/undionly.kpxe ../../artifacts/rpc-deploy-bootloader.kpxe
- mkdir -p efi_tmp
- dd if=/dev/zero of=efi_tmp/ipxe.img count=2880
- mformat -i efi_tmp/ipxe.img -m 0xf8 -f 2880
- mmd -i efi_tmp/ipxe.img ::efi ::efi/boot
- mcopy -i efi_tmp/ipxe.img bin-x86_64-efi/ipxe.efi ::efi/boot/bootx64.efi
- genisoimage -o ipxe.eiso -eltorito-alt-boot -e ipxe.img -no-emul-boot efi_tmp
- mv bin-x86_64-efi/ipxe.efi ../../artifacts/rpc-deploy-bootloader.efi
- mv ipxe.eiso ../../artifacts/rpc-deploy-bootloader-efi.iso
- cd ../../artifacts
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Antony Messerli"
  - git config --local user.email "amesserl@rackspace.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
  - rpc-deploy-bootloader.dsk
  - rpc-deploy-bootloader.iso
  - rpc-deploy-bootloader.lkrn
  - rpc-deploy-bootloader.usb
  - rpc-deploy-bootloader.kpxe
  - rpc-deploy-bootloader.kpxe
  - rpc-deploy-bootloader.efi
  - rpc-deploy-bootloader-efi.iso
  on:
    repo: rcbops/rpc-deploy
  skip_cleanup: true
